name: C++ Linting
run-name: ${{ gitea.actor }} is linting your code

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: host
    steps:
      - name: Use bash to setup
        shell: bash
        run: |
          apk update
          apk add nodejs python3 py3-pip gcc musl-dev python3-dev linux-headers make libffi-dev openssl-dev
          python3 -m pip install cpplint

  linter:
    needs: setup
    name: Linter
    runs-on: host
    steps:
      - name: Checkout sound_level_dba
        uses: actions/checkout@v4
      - name: Use bash to run linter
        shell: bash
        run: |
          cpplint --verbose=3 --extensions=ino sound_level_dba.ino